### ISSUE TITLE
[support]: PETSc fails built-in spack test

### ISSUE THREAD

**Issue by etpalmer63** [E4S-Project/e4s#125] opened 2023-05-23 14:23 UTC
### Name of Software

PETSc

### URL for Software

https://www.mcs.anl.gov/petsc/index.html

### Contact Details

epalmer@lbl.gov

### HPC System

NERSC Perlmutter

### Request Description

PETSc is fails its own built in spack test. It looks like it doesn't have the right permissions to create the test executable. I will investigate on my end as well. 

### Relevant log output

```shell
epalmer@perlmutter:login18:~> $ spack test run petsc
==> Spack test aoloej7iatub2tsxp5lxgokhik4luv3v
==> Testing package petsc-3.18.1-k3ngav3
==> Error: ProcessError: Command exited with status 2:
    'make' '-j1' 'ex50'

3 errors found in test log:
  >> 5    /usr/bin/ld: cannot open output file ex50: Permission denied
  >> 6    collect2: error: ld returned 1 exit status
  >> 7    make: *** [<builtin>: ex50] Error 1
     8    ==> [2023-05-23-07:00:11.970122] Completed testing

See test log for details:
  /global/homes/e/epalmer/.spack/test/aoloej7iatub2tsxp5lxgokhik4luv3v/petsc-3.18.1-k3ngav3-test-out.txt

======================== 1 failed, 0 passed of 1 specs =========================
==> Error: 1 test(s) in the suite failed.

epalmer@perlmutter:login18:~> $ spack test results -l aoloej7iatub2tsxp5lxgokhik4luv3v
==> Results for test suite 'aoloej7iatub2tsxp5lxgokhik4luv3v':
==> test specs:
==>   petsc-3.18.1-k3ngav3 FAILED
==> Testing package petsc-3.18.1-k3ngav3
==> [2023-05-23-07:00:09.724721] Installing /global/common/software/spackecp/perlmutter/e4s-22.11/83104/spack/opt/spack/linux-sles15-zen3/gcc-11.2.0/petsc-3.18.1-k3ngav3ud2vzg5xg2ykzu52j7rdzcfb7/.spack/test to /global/homes/e/epalmer/.spack/test/aoloej7iatub2tsxp5lxgokhik4luv3v/petsc-3.18.1-k3ngav3/cache/petsc
==> [2023-05-23-07:00:11.510897] 'make' '-j1' 'ex50'
/opt/cray/pe/mpich/default/ofi/gnu/9.1/bin/mpicc -fopenmp -fopenmp -fopenmp   -fPIC -Wall -Wwrite-strings -Wno-unknown-pragmas -Wno-lto-type-mismatch -Wno-stringop-overflow -fstack-protector -fvisibility=hidden -g -O  -I/global/common/software/spackecp/perlmutter/e4s-22.11/83104/spack/opt/spack/linux-sles15-zen3/gcc-11.2.0/petsc-3.18.1-k3ngav3ud2vzg5xg2ykzu52j7rdzcfb7/include -I/global/common/software/spackecp/perlmutter/e4s-22.11/83104/spack/opt/spack/linux-sles15-zen3/gcc-11.2.0/hypre-2.26.0-c3nzkgkk6yzs5scjoxs2gsdl7al7taul/include -I/global/common/software/spackecp/perlmutter/e4s-22.11/83104/spack/opt/spack/linux-sles15-zen3/gcc-11.2.0/strumpack-7.0.1-mbi2n6rzpyt5uymeozn7ulin3qzadshg/include -I/global/common/software/spackecp/perlmutter/e4s-22.11/83104/spack/opt/spack/linux-sles15-zen3/gcc-11.2.0/superlu-dist-8.1.1-j44lhovdwxobpfirivsuhluqxnzkmkrn/include -I/global/common/software/spackecp/perlmutter/e4s-22.11/83104/spack/opt/spack/linux-sles15-zen3/gcc-11.2.0/hdf5-1.12.2-jihwymm6vcr2nsq72vsjjizxnrqe2z6j/include -I/global/common/software/spackecp/perlmutter/e4s-22.11/83104/spack/opt/spack/linux-sles15-zen3/gcc-11.2.0/parmetis-4.0.3-b2mp26qn6hwg5nnj57l3js6zuabucf6c/include -I/global/common/software/spackecp/perlmutter/e4s-22.11/83104/spack/opt/spack/linux-sles15-zen3/gcc-11.2.0/metis-5.1.0-yp26rb6gorsk65zyr2gle63uzhljvdjo/include -I/global/common/software/spackecp/perlmutter/e4s-22.11/83104/spack/opt/spack/linux-sles15-zen3/gcc-11.2.0/zlib-1.2.13-76b2zrq6t4nwxof3yob7t6nedojgx4k5/include  -fopenmp   -export-dynamic ex50.c  -Wl,-rpath,/global/common/software/spackecp/perlmutter/e4s-22.11/83104/spack/opt/spack/linux-sles15-zen3/gcc-11.2.0/petsc-3.18.1-k3ngav3ud2vzg5xg2ykzu52j7rdzcfb7/lib -L/global/common/software/spackecp/perlmutter/e4s-22.11/83104/spack/opt/spack/linux-sles15-zen3/gcc-11.2.0/petsc-3.18.1-k3ngav3ud2vzg5xg2ykzu52j7rdzcfb7/lib -Wl,-rpath,/global/common/software/spackecp/perlmutter/e4s-22.11/83104/spack/opt/spack/linux-sles15-zen3/gcc-11.2.0/hypre-2.26.0-c3nzkgkk6yzs5scjoxs2gsdl7al7taul/lib -L/global/common/software/spackecp/perlmutter/e4s-22.11/83104/spack/opt/spack/linux-sles15-zen3/gcc-11.2.0/hypre-2.26.0-c3nzkgkk6yzs5scjoxs2gsdl7al7taul/lib -Wl,-rpath,/global/common/software/spackecp/perlmutter/e4s-22.11/83104/spack/opt/spack/linux-sles15-zen3/gcc-11.2.0/strumpack-7.0.1-mbi2n6rzpyt5uymeozn7ulin3qzadshg/lib64 -L/global/common/software/spackecp/perlmutter/e4s-22.11/83104/spack/opt/spack/linux-sles15-zen3/gcc-11.2.0/strumpack-7.0.1-mbi2n6rzpyt5uymeozn7ulin3qzadshg/lib64 -Wl,-rpath,/global/common/software/spackecp/perlmutter/e4s-22.11/83104/spack/opt/spack/linux-sles15-zen3/gcc-11.2.0/netlib-scalapack-2.2.0-esikbwiqb5mqfs46il7oxpmwdohtvr5g/lib -L/global/common/software/spackecp/perlmutter/e4s-22.11/83104/spack/opt/spack/linux-sles15-zen3/gcc-11.2.0/netlib-scalapack-2.2.0-esikbwiqb5mqfs46il7oxpmwdohtvr5g/lib -Wl,-rpath,/global/common/software/spackecp/perlmutter/e4s-22.11/83104/spack/opt/spack/linux-sles15-zen3/gcc-11.2.0/superlu-dist-8.1.1-j44lhovdwxobpfirivsuhluqxnzkmkrn/lib -L/global/common/software/spackecp/perlmutter/e4s-22.11/83104/spack/opt/spack/linux-sles15-zen3/gcc-11.2.0/superlu-dist-8.1.1-j44lhovdwxobpfirivsuhluqxnzkmkrn/lib -Wl,-rpath,/opt/cray/pe/libsci/default/GNU/9.1/x86_64/lib -L/opt/cray/pe/libsci/default/GNU/9.1/x86_64/lib -Wl,-rpath,/global/common/software/spackecp/perlmutter/e4s-22.11/83104/spack/opt/spack/linux-sles15-zen3/gcc-11.2.0/hdf5-1.12.2-jihwymm6vcr2nsq72vsjjizxnrqe2z6j/lib -L/global/common/software/spackecp/perlmutter/e4s-22.11/83104/spack/opt/spack/linux-sles15-zen3/gcc-11.2.0/hdf5-1.12.2-jihwymm6vcr2nsq72vsjjizxnrqe2z6j/lib -Wl,-rpath,/global/common/software/spackecp/perlmutter/e4s-22.11/83104/spack/opt/spack/linux-sles15-zen3/gcc-11.2.0/parmetis-4.0.3-b2mp26qn6hwg5nnj57l3js6zuabucf6c/lib -L/global/common/software/spackecp/perlmutter/e4s-22.11/83104/spack/opt/spack/linux-sles15-zen3/gcc-11.2.0/parmetis-4.0.3-b2mp26qn6hwg5nnj57l3js6zuabucf6c/lib -Wl,-rpath,/global/common/software/spackecp/perlmutter/e4s-22.11/83104/spack/opt/spack/linux-sles15-zen3/gcc-11.2.0/metis-5.1.0-yp26rb6gorsk65zyr2gle63uzhljvdjo/lib -L/global/common/software/spackecp/perlmutter/e4s-22.11/83104/spack/opt/spack/linux-sles15-zen3/gcc-11.2.0/metis-5.1.0-yp26rb6gorsk65zyr2gle63uzhljvdjo/lib -Wl,-rpath,/global/common/software/spackecp/perlmutter/e4s-22.11/83104/spack/opt/spack/linux-sles15-zen3/gcc-11.2.0/zlib-1.2.13-76b2zrq6t4nwxof3yob7t6nedojgx4k5/lib -L/global/common/software/spackecp/perlmutter/e4s-22.11/83104/spack/opt/spack/linux-sles15-zen3/gcc-11.2.0/zlib-1.2.13-76b2zrq6t4nwxof3yob7t6nedojgx4k5/lib -Wl,-rpath,/opt/cray/pe/mpich/8.1.22/ofi/gnu/9.1/lib -L/opt/cray/pe/mpich/8.1.22/ofi/gnu/9.1/lib -Wl,-rpath,/opt/cray/pe/libsci/22.11.1.2/GNU/9.1/x86_64/lib -L/opt/cray/pe/libsci/22.11.1.2/GNU/9.1/x86_64/lib -Wl,-rpath,/opt/nvidia/hpc_sdk/Linux_x86_64/21.11/cuda/11.5/lib64/stubs -L/opt/nvidia/hpc_sdk/Linux_x86_64/21.11/cuda/11.5/lib64/stubs -Wl,-rpath,/opt/nvidia/hpc_sdk/Linux_x86_64/21.11/cuda/11.5/lib64 -L/opt/nvidia/hpc_sdk/Linux_x86_64/21.11/cuda/11.5/lib64 -Wl,-rpath,/opt/nvidia/hpc_sdk/Linux_x86_64/21.11/cuda/11.5/nvvm/lib64 -L/opt/nvidia/hpc_sdk/Linux_x86_64/21.11/cuda/11.5/nvvm/lib64 -Wl,-rpath,/opt/nvidia/hpc_sdk/Linux_x86_64/21.11/cuda/11.5/extras/CUPTI/lib64 -L/opt/nvidia/hpc_sdk/Linux_x86_64/21.11/cuda/11.5/extras/CUPTI/lib64 -Wl,-rpath,/opt/nvidia/hpc_sdk/Linux_x86_64/21.11/cuda/11.5/extras/Debugger/lib64 -L/opt/nvidia/hpc_sdk/Linux_x86_64/21.11/cuda/11.5/extras/Debugger/lib64 -Wl,-rpath,/opt/nvidia/hpc_sdk/Linux_x86_64/21.11/math_libs/11.5/lib64 -L/opt/nvidia/hpc_sdk/Linux_x86_64/21.11/math_libs/11.5/lib64 -Wl,-rpath,/opt/cray/pe/dsmml/0.2.2/dsmml/lib -L/opt/cray/pe/dsmml/0.2.2/dsmml/lib -Wl,-rpath,/opt/cray/pe/pmi/6.1.7/lib -L/opt/cray/pe/pmi/6.1.7/lib -Wl,-rpath,/opt/cray/xpmem/2.5.2-2.4_3.20__gd0f7936.shasta/lib64 -L/opt/cray/xpmem/2.5.2-2.4_3.20__gd0f7936.shasta/lib64 -Wl,-rpath,/opt/cray/pe/gcc/11.2.0/snos/lib/gcc/x86_64-suse-linux/11.2.0 -L/opt/cray/pe/gcc/11.2.0/snos/lib/gcc/x86_64-suse-linux/11.2.0 -Wl,-rpath,/opt/cray/pe/gcc/11.2.0/snos/lib64 -L/opt/cray/pe/gcc/11.2.0/snos/lib64 -Wl,-rpath,/opt/cray/pe/gcc/11.2.0/snos/lib -L/opt/cray/pe/gcc/11.2.0/snos/lib -lpetsc -lHYPRE -lstrumpack -lscalapack -lsuperlu_dist -lsci_gnu -lhdf5_hl_fortran -lhdf5_hl_f90cstub -lhdf5_hl -lhdf5_fortran -lhdf5_f90cstub -lhdf5 -lparmetis -lmetis -lz -lstdc++ -ldl -lmpifort_gnu_91 -lmpi_gnu_91 -lcuda -lxpmem -lgfortran -lm -lcupti -lcudart -lsci_gnu_82_mpi -lsci_gnu_82 -ldsmml -lpmi -lpmi2 -lgfortran -lquadmath -lpthread -lm -lgcc_s -lquadmath -lstdc++ -ldl -o ex50
/usr/bin/ld: cannot open output file ex50: Permission denied
collect2: error: ld returned 1 exit status
make: *** [<builtin>: ex50] Error 1
==> [2023-05-23-07:00:11.970122] Completed testing

======================== 1 failed, 0 passed of 1 specs =========================


epalmer@perlmutter:login18:~> $ spack find -Lv petsc
==> In environment gcc
==> Root specs
-- no arch / gcc@11.2.0 -----------------------------------------
-------------------------------- adios2@2.8.3%gcc@11.2.0
-------------------------------- alquimia@1.0.10%gcc@11.2.0
-------------------------------- aml@0.2.0%gcc@11.2.0
-------------------------------- amrex@22.11%gcc@11.2.0
-------------------------------- arborx@1.3%gcc@11.2.0
-------------------------------- argobots@1.1%gcc@11.2.0
-------------------------------- autoconf%gcc@11.2.0
-------------------------------- automake%gcc@11.2.0
-------------------------------- axom@0.7.0%gcc@11.2.0
-------------------------------- bolt@2.0%gcc@11.2.0
-------------------------------- butterflypack@2.2.2%gcc@11.2.0
-------------------------------- cabana@0.5.0%gcc@11.2.0
-------------------------------- caliper@2.8.0%gcc@11.2.0
-------------------------------- cdo%gcc@11.2.0
-------------------------------- chai@2022.03.0%gcc@11.2.0 ~benchmarks~tests
-------------------------------- chapel@1.24.1%gcc@11.2.0
-------------------------------- cmake%gcc@11.2.0
-------------------------------- datatransferkit@3.1-rc3%gcc@11.2.0
-------------------------------- dyninst@12.2.0%gcc@11.2.0
-------------------------------- fftw@3.3.8%gcc@11.2.0
-------------------------------- fftw@3.3.9%gcc@11.2.0
-------------------------------- fftw@3.3.10%gcc@11.2.0
-------------------------------- flecsi@1.4.2%gcc@11.2.0
-------------------------------- flit@2.1.0%gcc@11.2.0
-------------------------------- flux-core@0.44.0%gcc@11.2.0
-------------------------------- fortrilinos@2.1.0%gcc@11.2.0
-------------------------------- gasnet@2022.9.0%gcc@11.2.0
-------------------------------- gawk%gcc@11.2.0
-------------------------------- ginkgo@1.4.0%gcc@11.2.0
-------------------------------- git%gcc@11.2.0
-------------------------------- globalarrays@5.8%gcc@11.2.0
-------------------------------- gmake%gcc@11.2.0
-------------------------------- gotcha@1.0.4%gcc@11.2.0
-------------------------------- gptune@3.0.0%gcc@11.2.0
-------------------------------- gromacs@2022.3%gcc@11.2.0
-------------------------------- gsl@2.7.1%gcc@11.2.0
-------------------------------- h5bench@1.3%gcc@11.2.0
-------------------------------- hdf5@1.12.2%gcc@11.2.0 +fortran+hl+shared
-------------------------------- hdf5-vol-async@1.3%gcc@11.2.0
-------------------------------- heffte@2.3.0%gcc@11.2.0 +fftw
-------------------------------- hpctoolkit@2022.10.01%gcc@11.2.0
-------------------------------- hpx@1.8.1%gcc@11.2.0  networking=mpi
-------------------------------- hypre@2.26.0%gcc@11.2.0
-------------------------------- intel-mkl%gcc@11.2.0
-------------------------------- kokkos@3.7.00%gcc@11.2.0 +openmp
-------------------------------- kokkos-kernels@3.7.00%gcc@11.2.0 +openmp
-------------------------------- lammps@20220623%gcc@11.2.0
-------------------------------- legion@21.03.0%gcc@11.2.0
-------------------------------- libcint%gcc@11.2.0
-------------------------------- libint%gcc@11.2.0  tune=molgw-lmax-7
-------------------------------- libquo@1.3.1%gcc@11.2.0
-------------------------------- libunwind@1.6.2%gcc@11.2.0
-------------------------------- libxc%gcc@11.2.0
-------------------------------- mercury@2.1.0%gcc@11.2.0
-------------------------------- metis@5.1.0%gcc@11.2.0
-------------------------------- mfem@4.5.0%gcc@11.2.0
-------------------------------- mpark-variant@1.4.0%gcc@11.2.0
-------------------------------- nano%gcc@11.2.0
-------------------------------- nccmp@1.9.0.1%gcc@11.2.0
-------------------------------- ncl%gcc@11.2.0
-------------------------------- nco%gcc@11.2.0
-------------------------------- nco@5.0.1%gcc@11.2.0
-------------------------------- ncview%gcc@11.2.0
-------------------------------- netcdf-c@4.9.0%gcc@11.2.0 ~mpi
-------------------------------- netcdf-fortran@4.6.0%gcc@11.2.0
-------------------------------- netlib-scalapack@2.2.0%gcc@11.2.0
-------------------------------- omega-h@9.34.13%gcc@11.2.0
-------------------------------- openblas@0.3.20%gcc@11.2.0  threads=openmp
-------------------------------- openpmd-api@0.14.5%gcc@11.2.0 ~adios2
-------------------------------- papi@6.0.0.1%gcc@11.2.0
-------------------------------- papyrus@1.0.2%gcc@11.2.0
-------------------------------- parallel-netcdf@1.12.3%gcc@11.2.0
-------------------------------- parmetis@4.0.3%gcc@11.2.0
-------------------------------- parsec@3.0.2209%gcc@11.2.0 ~cuda
-------------------------------- pdt@3.25.1%gcc@11.2.0
-------------------------------- petsc@3.18.1%gcc@11.2.0
-------------------------------- precice@2.5.0%gcc@11.2.0
-------------------------------- pumi@2.2.7%gcc@11.2.0
-------------------------------- py-h5py%gcc@11.2.0 ~mpi
-------------------------------- py-h5py%gcc@11.2.0 +mpi
-------------------------------- py-libensemble@0.9.3%gcc@11.2.0
-------------------------------- py-petsc4py@3.18.1%gcc@11.2.0
-------------------------------- py-warpx@22.10%gcc@11.2.0
-------------------------------- py-warpx@22.10%gcc@11.2.0
-------------------------------- py-warpx@22.10%gcc@11.2.0
-------------------------------- qt@5.14.2%gcc@11.2.0
-------------------------------- qthreads@1.16%gcc@11.2.0  scheduler=distrib
-------------------------------- quantum-espresso@7.1%gcc@11.2.0
-------------------------------- raja@2022.03.0%gcc@11.2.0
-------------------------------- slate@2022.07.0%gcc@11.2.0 ~cuda
-------------------------------- slepc@3.18.1%gcc@11.2.0
-------------------------------- strumpack@7.0.1%gcc@11.2.0 ~slate
-------------------------------- subversion%gcc@11.2.0
-------------------------------- sundials@6.4.1%gcc@11.2.0
-------------------------------- superlu@5.3.0%gcc@11.2.0
-------------------------------- superlu-dist@8.1.1%gcc@11.2.0
-------------------------------- tasmanian@7.9%gcc@11.2.0
-------------------------------- tau@2.32%gcc@11.2.0 +mpi+python
-------------------------------- trilinos@13.0.1%gcc@11.2.0 +amesos+amesos2+anasazi+aztec+belos+boost+epetra+epetraext+ifpack+ifpack2+intrepid+intrepid2+isorropia+kokkos+minitensor+ml+muelu+nox+phalanx+piro+rol+rythmos+sacado+shards+shylu+stk+stokhos+stratimikos+superlu-dist+teko+tempus+tpetra+trilinoscouplings+zoltan+zoltan2 gotype=long_long
-------------------------------- umap@2.1.0%gcc@11.2.0
-------------------------------- umpire@2022.03.1%gcc@11.2.0
-------------------------------- upcxx@2022.9.0%gcc@11.2.0
-------------------------------- vtk-m@1.9.0%gcc@11.2.0
-------------------------------- zfp@0.5.5%gcc@11.2.0

==> Installed packages
-- linux-sles15-zen3 / gcc@11.2.0 -------------------------------
k3ngav3ud2vzg5xg2ykzu52j7rdzcfb7 petsc@3.18.1~X~batch~cgns~complex~cuda~debug+double~exodusii~fftw+fortran~giflib+hdf5~hpddm~hwloc+hypre~int64~jpeg~knl~kokkos~libpng~libyaml~memkind+metis~mkl-pardiso~mmg~moab~mpfr+mpi~mumps+openmp~p4est~parmmg~ptscotch~random123~rocm~saws~scalapack+shared+strumpack~suite-sparse+superlu-dist~tetgen~trilinos~valgrind build_system=generic clanguage=C
==> 1 installed package
```

### Reproduce Bug

```bash
1. module load e4s
2. spack env activate gcc
3. spack load petsc
4. spack test run petsc
...
```

**Comment by shahzebsiddiqui** [comment] 2023-05-23 14:26
@etpalmer63 can you share the output of `spack test results -l -- petsc`. That would be helpful in debugging. I have seen permission errors with some test. This might be just one of them.

Also can you share output of `ml`. That would be helpful

**Comment by eugeneswalker** [comment] 2023-05-23 16:11
Hi Erik, thanks for reporting this.

Do you know from what working directory `mpicc ... -o ex50` in your output is being run from? 

```
epalmer@perlmutter:login18:~> $ spack test results -l aoloej7iatub2tsxp5lxgokhik4luv3v
==> Results for test suite 'aoloej7iatub2tsxp5lxgokhik4luv3v':
==> test specs:
==>   petsc-3.18.1-k3ngav3 FAILED
...
/opt/cray/pe/mpich/default/ofi/gnu/9.1/bin/mpicc ... -o ex50
/usr/bin/ld: cannot open output file ex50: Permission denied
```

Looking at the second from last line there:
```
/opt/cray/pe/mpich/default/ofi/gnu/9.1/bin/mpicc ... -o ex50
```

**Comment by etpalmer63** [comment] 2023-05-23 16:34
From the Spack recipe file: 

`664         w_dir = join_path(self.install_test_root, "src/ksp/ksp/tutorials")`

So it looks like its trying to build the test in:

`.spack/test/aoloej7iatub2tsxp5lxgokhik4luv3v/petsc-3.18.1-k3ngav3/cache/petsc/src/ksp/ksp/tutorials`

**Comment by wspear** [comment] 2023-05-23 17:23
I've cross-linked this issue to the spack issue tracker at https://github.com/spack/spack/issues/37872 and tagged the package maintainers. 

Note that for spack test issues it is generally more efficient to create issues on the spack repo tracker and cross-link them to e4s rather than vice versa, since these are spack issues that will be fixed with spack PRs. They even have a template for spack test failure reports.

**Comment by tldahlgren** [comment] 2023-05-23 19:37
This is a known issue.  I have preliminary work to do the conversion to the new Spack syntax (https://github.com/spack/spack/pull/35754) that I need to update now that the feature has been released.  I will also pull the package out into its own PR.

**Comment by eugeneswalker** [comment] 2023-11-02 18:00
This test issue should be resolved now with changes both to `spack test` and specifically to `petsc`'s Spack test function merged in upstream Spack. Are you able to confirm the issue is resolved using a recent commit of Spack?

**Comment by eugeneswalker** [comment] 2023-12-04 18:20
Closing this issue as resolved. If you find the issue is not resolved, we will re-open.

**Closed by eugeneswalker** 2023-12-04 18:20 UTC
Labels: support
