### ISSUE TITLE
[support]: SuperLU fails built-in Spack test

### ISSUE THREAD

**Issue by etpalmer63** [E4S-Project/e4s#127] opened 2023-06-01 16:03 UTC
### Name of Software

SuperLU

### URL for Software

https://portal.nersc.gov/project/sparse/superlu/

### Contact Details

epalmer@lbl.gov

### HPC System

NERSC Perlmutter

### Request Description

SuperLU fails the self test. Cross-Ref to the Spack Issue: https://github.com/spack/spack/issues/38051

Looks like another permissions issue with the file creation, possible similar to https://github.com/E4S-Project/e4s/issues/125

@shahzebsiddiqui , is this an issue with the permissions on the folders Spack is running the tests in that we can fix on our end? 

### Relevant log output

```shell
==> Installed packages
-- linux-sles15-zen3 / gcc@11.2.0 -------------------------------
tnurd2ul2lqav4gc4nj3yla5yxdkyud6 superlu@5.3.0~ipo+pic build_system=cmake build_type=RelWithDebInfo
==> 1 installed package

epalmer@perlmutter:login23:~> $ spack load superlu
epalmer@perlmutter:login23:~> $ spack test run superlu
==> Spack test r6smlz4irtbq3uoqdbojqmd7etj6aj4d
==> Testing package superlu-5.3.0-tnurd2u
==> Error: FileNotFoundError: [Errno 2] No such file or directory: '/global/homes/e/epalmer/.spack/test/r6smlz4irtbq3uoqdbojqmd7etj6aj4d/superlu-5.3.0-tnurd2u/cache/superlu/make.inc'

/global/common/software/spackecp/perlmutter/e4s-22.11/83104/spack/var/spack/repos/builtin/packages/superlu/package.py:142, in test:
        139
        140        # Write configuration options to make.inc file
        141        make_file_inc = join_path(self.test_suite.current_test_cache_dir, self.make_hdr_file)
  >>    142        with open(make_file_inc, "w") as inc:
        143            for option in config_args:
        144                inc.write("{0}\n".format(option))
        145

See test log for details:
  /global/homes/e/epalmer/.spack/test/r6smlz4irtbq3uoqdbojqmd7etj6aj4d/superlu-5.3.0-tnurd2u-test-out.txt

======================== 1 failed, 0 passed of 1 specs =========================
==> Error: 1 test(s) in the suite failed.

epalmer@perlmutter:login23:~> $ spack test results -l r6smlz4irtbq3uoqdbojqmd7etj6aj4d
==> Results for test suite 'r6smlz4irtbq3uoqdbojqmd7etj6aj4d':
==> test specs:
==>   superlu-5.3.0-tnurd2u FAILED
==> Testing package superlu-5.3.0-tnurd2u
==> [2023-06-01-08:37:17.763814] Completed testing

======================== 1 failed, 0 passed of 1 specs =========================


epalmer@perlmutter:login23:~> $ ml -t
craype-x86-milan
libfabric/1.15.2.0
craype-network-ofi
xpmem/2.5.2-2.4_3.47__gd0f7936.shasta
PrgEnv-gnu/8.3.3
cray-dsmml/0.2.2
cray-libsci/23.02.1.1
cray-mpich/8.1.25
craype/2.7.20
gcc/11.2.0
perftools-base/23.03.0
cpe/23.03
xalt/2.10.2
Nsight-Compute/2022.1.1
Nsight-Systems/2022.2.1
cudatoolkit/11.7
craype-accel-nvidia80
gpu/1.0
```

### Reproduce Bug

```bash
1. Login to Perlmutter
2. module load e4s/21.11
3. spack env activate gcc
4. spack load superlu
5. spack test run superlu
...
```

**Comment by sameershende** [comment] 2023-06-01 16:14
I acknowledge this issue. We will investigate and find a solution. Thanks for reporting this issue.

**Comment by eugeneswalker** [comment] 2023-11-02 17:59
This issue should be resolved with changes to both `spack test` and specifically the `superlu-dist` Spack merged to upstream Spack. Are you able to try again with a recent commit of Spack?

**Comment by eugeneswalker** [comment] 2023-12-04 18:20
Closing this issue as resolved. If you find the issue is not resolved, we will re-open.

**Closed by eugeneswalker** 2023-12-04 18:20 UTC
Labels: support
